
import React, { useState } from 'react';
import { Bell, Plus, Trash2, Calendar, Check, Tag, Sparkles, Loader2, X, Wand2 } from 'lucide-react';
import { Notice } from '../types';
import { GoogleGenAI } from "@google/genai";

interface ManageNoticesProps {
  notices: Notice[];
  onAdd: (notice: Notice) => void;
  onDelete: (id: string) => void;
}

const ManageNotices: React.FC<ManageNoticesProps> = ({ notices, onAdd, onDelete }) => {
  const [formData, setFormData] = useState({
    title: '',
    date: new Date().toISOString().split('T')[0],
    type: 'General'
  });

  const [message, setMessage] = useState<{ type: 'success' | 'error', text: string } | null>(null);

  // AI State
  const [showAiInput, setShowAiInput] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.title) {
        setMessage({ type: 'error', text: 'Notice title is required.' });
        return;
    }
    const dateObj = new Date(formData.date);
    const formattedDate = dateObj.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
    const newNotice: Notice = {
        id: Date.now().toString(),
        title: formData.title,
        date: formattedDate,
        type: formData.type
    };
    onAdd(newNotice);
    setMessage({ type: 'success', text: 'Notice published successfully!' });
    setFormData({
        title: '',
        date: new Date().toISOString().split('T')[0],
        type: 'General'
    });
    setTimeout(() => setMessage(null), 3000);
  };

  const handleAiGenerate = async () => {
    if (!aiPrompt.trim()) return;
    
    // Safety check for API Key presence
    if (!process.env.API_KEY) {
         setMessage({ type: 'error', text: 'API Key missing. AI features disabled.' });
         return;
    }
    
    setIsGenerating(true);
    try {
        const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
        const response = await ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: `Write a professional, concise school notice (max 30 words) based on this topic: "${aiPrompt}". It should be ready to publish as an announcement title/body. Return only the text.`,
        });

        const generatedText = response.text?.trim();
        if (generatedText) {
            setFormData(prev => ({ ...prev, title: generatedText }));
            setShowAiInput(false);
            setAiPrompt('');
            setMessage({ type: 'success', text: 'Notice generated by AI!' });
            setTimeout(() => setMessage(null), 3000);
        }
    } catch (error) {
        console.error("AI Generation Error:", error);
        setMessage({ type: 'error', text: 'Failed to generate notice. Please try again.' });
    } finally {
        setIsGenerating(false);
    }
  };

  const noticeTypes = ['General', 'Holiday', 'Exams', 'Sports', 'Meeting', 'Academic'];

  return (
    <div className="max-w-6xl mx-auto space-y-6 animate-in fade-in duration-500">
       <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-800">Manage Notices</h1>
        <p className="text-sm text-gray-500">Publish announcements for students and staff</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-1">
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 h-fit sticky top-6">
                <div className="flex items-center justify-between mb-6">
                    <h3 className="font-bold text-gray-800 flex items-center gap-2">
                        <Plus size={18} className="text-[#5e81f4]" />
                        New Notice
                    </h3>
                    <button 
                        onClick={() => setShowAiInput(!showAiInput)}
                        className={`p-2 rounded-lg transition-all ${showAiInput ? 'bg-indigo-100 text-indigo-600' : 'bg-gray-50 text-gray-400 hover:text-indigo-500 hover:bg-indigo-50'}`}
                        title="AI Assistant"
                    >
                        <Sparkles size={16} />
                    </button>
                </div>

                {message && (
                    <div className={`mb-4 p-3 rounded-lg text-sm flex items-center gap-2 ${message.type === 'success' ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'}`}>
                        <Check size={16} />
                        {message.text}
                    </div>
                )}

                {showAiInput && (
                    <div className="mb-6 p-4 bg-indigo-50 rounded-xl border border-indigo-100 animate-in slide-in-from-top-2">
                        <div className="flex justify-between items-center mb-2">
                             <label className="text-[10px] font-black text-indigo-400 uppercase tracking-widest flex items-center gap-1">
                                <Wand2 size={12} /> AI Generator
                             </label>
                             <button onClick={() => setShowAiInput(false)} className="text-indigo-300 hover:text-indigo-600">
                                <X size={14} />
                             </button>
                        </div>
                        <div className="flex gap-2">
                            <input 
                                type="text"
                                value={aiPrompt}
                                onChange={(e) => setAiPrompt(e.target.value)}
                                placeholder="e.g. Sports Day on Friday..."
                                className="flex-1 px-3 py-2 bg-white border border-indigo-200 rounded-lg text-xs font-medium focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
                                onKeyDown={(e) => e.key === 'Enter' && handleAiGenerate()}
                            />
                            <button 
                                onClick={handleAiGenerate}
                                disabled={isGenerating || !aiPrompt.trim()}
                                className="px-3 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 transition-colors"
                            >
                                {isGenerating ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
                            </button>
                        </div>
                    </div>
                )}

                <form onSubmit={handleSubmit} className="space-y-4">
                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase mb-1.5">Notice Content</label>
                        <textarea 
                            value={formData.title}
                            onChange={(e) => setFormData({...formData, title: e.target.value})}
                            className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#5e81f4] focus:border-transparent text-sm min-h-[100px]"
                            placeholder="Type your announcement here..."
                            required
                        />
                    </div>
                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase mb-1.5">Date</label>
                        <div className="relative">
                            <input 
                                type="date" 
                                value={formData.date}
                                onChange={(e) => setFormData({...formData, date: e.target.value})}
                                className="w-full pl-4 pr-12 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#5e81f4] focus:border-transparent text-sm"
                            />
                            <Calendar className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" size={16} />
                        </div>
                    </div>
                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase mb-1.5">Type</label>
                        <div className="relative">
                            <select 
                                value={formData.type}
                                onChange={(e) => setFormData({...formData, type: e.target.value})}
                                className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#5e81f4] focus:border-transparent text-sm bg-white"
                            >
                                {noticeTypes.map(t => (
                                    <option key={t} value={t}>{t}</option>
                                ))}
                            </select>
                            <Tag className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" size={16} />
                        </div>
                    </div>
                    <button 
                        type="submit" 
                        className="w-full py-2.5 bg-[#5e81f4] hover:bg-[#4b69c6] text-white font-bold rounded-lg shadow-sm transition-colors flex items-center justify-center gap-2 mt-2"
                    >
                        <Bell size={16} />
                        Publish Notice
                    </button>
                </form>
            </div>
        </div>

        <div className="lg:col-span-2 space-y-4">
            <h3 className="font-bold text-gray-800 mb-2">Active Notices</h3>
            {notices.length > 0 ? notices.map((notice) => (
                <div key={notice.id} className="bg-white rounded-xl shadow-sm border border-gray-200 p-5 flex items-start justify-between group hover:border-[#5e81f4] transition-colors">
                    <div className="flex gap-4">
                        <div className="h-12 w-12 bg-gray-50 rounded-lg flex flex-col items-center justify-center border border-gray-100 shrink-0">
                             <Bell size={18} className="text-[#5e81f4] mb-1" />
                        </div>
                        <div>
                            <h4 className="font-semibold text-gray-800 text-sm mb-1">{notice.title}</h4>
                            <div className="flex items-center gap-3 text-xs text-gray-500">
                                <span className="flex items-center gap-1">
                                    <Calendar size={12} /> {notice.date}
                                </span>
                                <span className={`px-2 py-0.5 rounded-md font-medium
                                    ${notice.type === 'Holiday' ? 'bg-red-50 text-red-600' : 
                                      notice.type === 'Exams' ? 'bg-amber-50 text-amber-600' :
                                      'bg-blue-50 text-blue-600'}
                                `}>
                                    {notice.type}
                                </span>
                            </div>
                        </div>
                    </div>
                    <button 
                        onClick={() => onDelete(notice.id)}
                        className="p-2 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors opacity-0 group-hover:opacity-100"
                        title="Delete Notice"
                    >
                        <Trash2 size={18} />
                    </button>
                </div>
            )) : (
                <div className="bg-white rounded-xl border border-dashed border-gray-200 p-12 text-center text-gray-400">
                    <Bell size={48} className="mx-auto mb-3 opacity-20" />
                    <p className="font-medium">No notices published yet.</p>
                </div>
            )}
        </div>
      </div>
    </div>
  );
};

export default ManageNotices;
